<?php

/**
 * @file
 * Primary module hooks for Localgov alert banner collapsible module.
 */

/**
 * Implements hook_theme().
 */
function localgov_alert_banner_collapsible_theme(): array {
  return [
    'localgov_alert_banner_collapsible' => [
      'variables' => [
        'control' => NULL,
        'banners' => NULL,
        'persistent_banners' => NULL,
        'html_id' => NULL,
        'count' => NULL,
        'summary' => NULL,
        'closed_label' => NULL,
        'open_label' => NULL,
        'published_alert_banners' => NULL,
        'banner_titles' => NULL,
        'default_state' => NULL,
      ],
    ],
  ];
}
